### ISSUE TITLE
Slides

### ISSUE THREAD

**Issue by juanshishido** [deniederhut/workshop_bots#2]
Looking at http://www.slideviper.oquanta.info/tutorial/slideshow_tutorial_slides.html for converting the notebook into slides.

Would be useful having slides that directly follow what participants see in the notebook.

**Comment by deniederhut** [comment]
Since you uploaded the notebook, I had assumed you were planning on doing an interactive demo within the notebook. It should be easy enough to copy and paste the text into Rmd, although we won't be able to evaluate any of the python code within the slides.

**Comment by juanshishido** [comment]
Yeah, good call. At this point, let's just roll with the notebook. Thanks!
