### ISSUE TITLE
Can we add the twitter handle of the class's bot to the notebook?

### ISSUE THREAD

**Issue by deniederhut** [deniederhut/workshop_bots#3]
Also, just a security thing, it's probably better not to have the credentials on github. A more secure solution would be to have the notebook read in the credentials from a file, and email the file to folks in the class. This might be too complicated for folks that are new to this though.

**Comment by juanshishido** [comment]
Thanks for the suggestion, @deniederhut. I totally agree with you on the credentials. With the D-Lab's Twitter bot, I used a config file to handle that. For this project, and for the reason you mention of it potentially being too complicated, I decided to just have it open.

Agree that it feels strange.

Also, Twitter handle added. Here is the profile page: https://twitter.com/tob_pohskrow.
